### ISSUE TITLE
Seeso Web SDK compatibility on mobile/tablet devices

### ISSUE THREAD

**Issue by jespa007** [visualcamp/seeso-sample-web#4]
The client with Seeso Web SDK works on desktop environments but it seems it doesn't on mobile/tablet devices.

Do you know any mobile or tablet brand that have tested that Seeso Web SDK works ? In case not, do you know if Seeso Web SDK is expected to have compatbility on mobile devices  in the future ? 

It would be great

**Comment by leeyongeun9** [comment]
Hi @jespa007, we tested Samsung Galaxy Tab S7 with chrome browser.
The browser must support [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
) feature for SeeSo.
There is nothing we can do to make seeso work in mobile browsers.
We have to wait for the feature in the link above to be supported in each browser.

**Comment by code-xhyun** [comment]
@jespa007 
You can check for support on this site

[https://caniuse.com/?search=SharedArrayBuffer](https://caniuse.com/?search=SharedArrayBuffer)
